name: Emotion CF (conda)

on:
  push:
    branches:
      - paper_updates

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Download and setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies and Run Tests
        shell: bash -l {0}
        run: |
          conda init bash
          conda activate test
          conda env list
          conda install -y pip numpy pandas scipy matplotlib seaborn scikit-learn
          conda install -y -c conda-forge pytest pytest-xdist
          pip install -r requirements.txt
          pytest -s -n auto

      # - name: Coveralls
      #   uses: coverallsapp/github-action@master
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
